### ISSUE TITLE
Typo in SampleGrid.R

### ISSUE THREAD

**Issue by whipson** [jmbh/ARVAR#1]
In SampleGrid.R line 42 there is a typo (missing 'h') in the file path for MindMaastricht data.

#Original code in repo
`Laura_mm <- readRDS("files/MM_MindMaastrict.RDS")`

#Revision
`Laura_mm <- readRDS("files/MM_MindMaastricht.RDS")`

**Comment by jmbh** [comment]
Fixed, thanks!
